import { Moon, BookOpen, Music, Coffee, Shirt, Waves, Dumbbell, Bike, Activity, TrendingUp, Zap, Clock, BedDouble } from 'lucide-react'

export const CATEGORIES = ['Health', 'Hobbies', 'Learning']

export const HABITS = [
  {
    id: 'sleep',
    name: 'Sleep',
    unit: 'hours',
    icon: Moon,
    color: '#7b2ff7',
    category: 'Health',
  },
  {
    id: 'solidcore',
    name: 'Strength Training',
    unit: 'sessions',
    aggregate: 'sum',
    icon: Dumbbell,
    color: '#f43f5e',
    category: 'Health',
  },
  {
    id: 'dance',
    name: 'Dance Practice',
    unit: 'min',
    displayUnit: 'hours',
    displayFactor: 1 / 60,
    icon: Music,
    color: '#f72585',
    category: 'Hobbies',
    staffOnly: true,
  },
  {
    id: 'fit_checks',
    name: 'Fit Checks',
    unit: 'fits',
    aggregate: 'sum',
    icon: Shirt,
    color: '#facc15',
    category: 'Hobbies',
  },
  {
    id: 'kayaking',
    name: 'Water Sports',
    unit: 'voyages',
    aggregate: 'sum',
    icon: Waves,
    color: '#4cc9f0',
    category: 'Hobbies',
  },
  {
    id: 'cycling',
    name: 'Cycling',
    unit: 'sessions',
    aggregate: 'sum',
    icon: Bike,
    color: '#38bdf8',
    category: 'Health',
  },
  {
    id: 'articles',
    name: 'Articles Read',
    unit: 'articles',
    aggregate: 'sum',
    subtitle: 'to be updated; automatic integration forthcoming',
    icon: BookOpen,
    color: '#4ade80',
    category: 'Learning',
    staffOnly: true,
  },
  {
    id: 'coffee_chats',
    name: 'Coffee Chats',
    unit: 'chats',
    aggregate: 'sum',
    icon: Coffee,
    color: '#fb923c',
    category: 'Learning',
  },
  {
    id: 'glucose_avg',
    name: 'Avg Glucose',
    unit: 'mg/dL',
    icon: Activity,
    color: '#a78bfa',
    category: 'Health',
    staffOnly: true,
  },
  {
    id: 'glucose_tir',
    name: 'Time in Range',
    subtitle: '70–140 mg/dL',
    unit: '%',
    icon: TrendingUp,
    color: '#34d399',
    category: 'Health',
    staffOnly: true,
  },
  {
    id: 'glucose_excursions',
    name: 'Glucose Excursions',
    subtitle: 'times crossing above 140 mg/dL',
    unit: 'excursions',
    aggregate: 'sum',
    icon: Zap,
    color: '#fb7185',
    category: 'Health',
    staffOnly: true,
  },
  {
    id: 'on_time',
    name: 'On Time',
    subtitle: 'number of times I have been on time',
    unit: 'times',
    aggregate: 'sum',
    icon: Clock,
    color: '#a3a3a3',
    category: 'Learning',
    staffOnly: true,
  },
  {
    id: 'early_bedtime',
    name: 'Early Bedtime',
    subtitle: 'number of times I have gone to bed early',
    unit: 'times',
    aggregate: 'sum',
    icon: BedDouble,
    color: '#8b5cf6',
    category: 'Health',
  },
]
